# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W42cAcWdPzT5Bj5_C7ik4RVgnklor3Dq
"""

import nltk
nltk.download('vader_lexicon')


import pandas as pd
from nltk.sentiment import SentimentIntensityAnalyzer



from google.colab import files
type(data)

data = 'Reddit_Data.xlsx'
from google.colab import files

uploaded = files.upload()
print(data)

data = pd.read_excel('Reddit_Data.xlsx')

data['clean_text'] = data['clean_text'].astype(str)


sia = SentimentIntensityAnalyzer()
data['sentiment_score'] = data['clean_text'].apply(lambda x: sia.polarity_scores(x)['compound'])
data['is_depressive'] = data['sentiment_score'].apply(lambda x: 1 if x < -0.5 else 0)




depressive_posts = data[data['sentiment_score'] < -0.5]
num_depressive_posts = len(depressive_posts)
print("Number of depressive posts:", num_depressive_posts)

depressive_posts = data[data['sentiment_score'] < -0.5]
depressive_texts = depressive_posts['clean_text'].tolist()

for text in depressive_texts:
    print(text)

